package te050c.app;

import te050c.tl.Form;
import te050c.tl.TL;
import te050c.tl.Util;
import te050c.tl.db.tbl.*;

import java.lang.reflect.Field;

import java.util.List;
import java.util.Map;

/**
 * Created by moh on 18/12/16.
 */
public class Income extends Tbl {

@Override public List creationDBTIndices(TL tl){
	return Util.lst(Util.lst(
			" int(11) NOT NULL AUTO_INCREMENT"//`row`
  ,"int(11) NOT NULL"//FS_ID
	 ,"int(11) DEFAULT NULL"//RECORD_ID
,"int(11) DEFAULT NULL"//TABLE_ID
,"int(11) DEFAULT NULL"//FSCYCLE
,"int(11) DEFAULT NULL"//MEM_ID
,"varchar(1) DEFAULT NULL"//FM_MM
,"int(11) DEFAULT NULL"//SALRY_1
,"int(11) DEFAULT NULL"//SALRY_2
,"int(11) DEFAULT NULL"//BONCE_1
,"int(11) DEFAULT NULL"//BONCE_2
,"int(11) DEFAULT NULL"//ALLOW_1
,"int(11) DEFAULT NULL"//ALLOW_2
,"int(11) DEFAULT NULL"//INCOME1
,"int(11) DEFAULT NULL"//INDUST
,"int(11) DEFAULT NULL"//COMMERCE
,"int(11) DEFAULT NULL"//TRANS
,"int(11) DEFAULT NULL"//CONSTRANT
,"int(11) DEFAULT NULL"//FAINANCE
,"int(11) DEFAULT NULL"//OWNWRK
,"int(11) DEFAULT NULL"//OTHERS
,"int(11) DEFAULT NULL"//INCOME2
,"int(11) DEFAULT NULL"//DIVIDENDS
,"int(11) DEFAULT NULL"//BONDS
,"int(11) DEFAULT NULL"//SAVINGAC
,"int(11) DEFAULT NULL"//INVESTMENT
,"int(11) DEFAULT NULL"//INCOME3
,"int(11) DEFAULT NULL"//LANDRENT
,"int(11) DEFAULT NULL"//PROJCTRENT
,"int(11) DEFAULT NULL"//MACHNRENT
,"int(11) DEFAULT NULL"//CPYRIGHT
,"int(11) DEFAULT NULL"//INCOME4
,"int(11) DEFAULT NULL"//MARIGGIFT
,"int(11) DEFAULT NULL"//RETIREDSAL
,"int(11) DEFAULT NULL"//TRETGRANT
,"int(11) DEFAULT NULL"//SOCILASST
,"int(11) DEFAULT NULL"//UNEMPALOW
,"int(11) DEFAULT NULL"//RENTALLOW
,"int(11) DEFAULT NULL"//OTHRGRANT
,"int(11) DEFAULT NULL"//INCOME5
,"int(11) DEFAULT NULL"//ACC_COMP
,"int(11) DEFAULT NULL"//LIFEINSUR
,"int(11) DEFAULT NULL"//REMTABROD
,"int(11) DEFAULT NULL"//REMTINSDE
,"int(11) DEFAULT NULL"//LEGITEXP
,"int(11) DEFAULT NULL"//CASHGIFT
,"int(11) DEFAULT NULL"//KINDGIFT
,"int(11) DEFAULT NULL"//INCOME6
,"int(11) DEFAULT NULL"//CSHINHERIT
,"int(11) DEFAULT NULL"//DOWRY
,"int(11) DEFAULT NULL"//SATELDLOAN
,"int(11) DEFAULT NULL"//SELGOODS
,"int(11) DEFAULT NULL"//LIFEINSRNC
,"int(11) DEFAULT NULL"//WITHDRAWS
,"int(11) DEFAULT NULL"//OTHERPROC
,"int(11) DEFAULT NULL"//INCOME7
,"int(11) DEFAULT NULL"//DEPOSIT
,"int(11) DEFAULT NULL"//WITHDRAW
,"int(11) DEFAULT NULL"//LENDING
,"int(11) DEFAULT NULL"//BORRWING
,"int(11) DEFAULT NULL"//PROCEEDS
,"int(11) DEFAULT NULL"//PAYMENTS
,"int(11) DEFAULT NULL"//SELSCRTIS
,"int(11) DEFAULT NULL"//BUYSCRTIS
,"int(11) DEFAULT NULL"//SELLAND
,"int(11) DEFAULT NULL"//BUYLAND
,"int(11) DEFAULT NULL"//SELBUILD
,"int(11) DEFAULT NULL"//BUYBUILD
,"int(11) DEFAULT NULL"//SELOTHER
,"int(11) DEFAULT NULL"//BUYOTHER
,"int(11) DEFAULT NULL"//INCOME8
));

	/*
CREATE TABLE `memberincome` (
  `row` int(11) NOT NULL AUTO_INCREMENT,
  `FS_ID` int(11) NOT NULL,
  `RECORD_ID` int(11) DEFAULT NULL,
  `TABLE_ID` int(11) DEFAULT NULL,
  `FSCYCLE` int(11) DEFAULT NULL,
  `MEM_ID` int(11) DEFAULT NULL,
  `FM_MM` varchar(1) DEFAULT NULL,
  `SALRY_1` int(11) DEFAULT NULL,
  `SALRY_2` int(11) DEFAULT NULL,
  `BONCE_1` int(11) DEFAULT NULL,
  `BONCE_2` int(11) DEFAULT NULL,
  `ALLOW_1` int(11) DEFAULT NULL,
  `ALLOW_2` int(11) DEFAULT NULL,
  `INCOME1` int(11) DEFAULT NULL,
  `INDUST` int(11) DEFAULT NULL,
  `COMMERCE` int(11) DEFAULT NULL,
  `TRANS` int(11) DEFAULT NULL,
  `CONSTRANT` int(11) DEFAULT NULL,
  `FAINANCE` int(11) DEFAULT NULL,
  `OWNWRK` int(11) DEFAULT NULL,
  `OTHERS` int(11) DEFAULT NULL,
  `INCOME2` int(11) DEFAULT NULL,
  `DIVIDENDS` int(11) DEFAULT NULL,
  `BONDS` int(11) DEFAULT NULL,
  `SAVINGAC` int(11) DEFAULT NULL,
  `INVESTMENT` int(11) DEFAULT NULL,
  `INCOME3` int(11) DEFAULT NULL,
  `LANDRENT` int(11) DEFAULT NULL,
  `PROJCTRENT` int(11) DEFAULT NULL,
  `MACHNRENT` int(11) DEFAULT NULL,
  `CPYRIGHT` int(11) DEFAULT NULL,
  `INCOME4` int(11) DEFAULT NULL,
  `MARIGGIFT` int(11) DEFAULT NULL,
  `RETIREDSAL` int(11) DEFAULT NULL,
  `TRETGRANT` int(11) DEFAULT NULL,
  `SOCILASST` int(11) DEFAULT NULL,
  `UNEMPALOW` int(11) DEFAULT NULL,
  `RENTALLOW` int(11) DEFAULT NULL,
  `OTHRGRANT` int(11) DEFAULT NULL,
  `INCOME5` int(11) DEFAULT NULL,
  `ACC_COMP` int(11) DEFAULT NULL,
  `LIFEINSUR` int(11) DEFAULT NULL,
  `REMTABROD` int(11) DEFAULT NULL,
  `REMTINSDE` int(11) DEFAULT NULL,
  `LEGITEXP` int(11) DEFAULT NULL,
  `CASHGIFT` int(11) DEFAULT NULL,
  `KINDGIFT` int(11) DEFAULT NULL,
  `INCOME6` int(11) DEFAULT NULL,
  `CSHINHERIT` int(11) DEFAULT NULL,
  `DOWRY` int(11) DEFAULT NULL,
  `SATELDLOAN` int(11) DEFAULT NULL,
  `SELGOODS` int(11) DEFAULT NULL,
  `LIFEINSRNC` int(11) DEFAULT NULL,
  `WITHDRAWS` int(11) DEFAULT NULL,
  `OTHERPROC` int(11) DEFAULT NULL,
  `INCOME7` int(11) DEFAULT NULL,
  `DEPOSIT` int(11) DEFAULT NULL,
  `WITHDRAW` int(11) DEFAULT NULL,
  `LENDING` int(11) DEFAULT NULL,
  `BORRWING` int(11) DEFAULT NULL,
  `PROCEEDS` int(11) DEFAULT NULL,
  `PAYMENTS` int(11) DEFAULT NULL,
  `SELSCRTIS` int(11) DEFAULT NULL,
  `BUYSCRTIS` int(11) DEFAULT NULL,
  `SELLAND` int(11) DEFAULT NULL,
  `BUYLAND` int(11) DEFAULT NULL,
  `SELBUILD` int(11) DEFAULT NULL,
  `BUYBUILD` int(11) DEFAULT NULL,
  `SELOTHER` int(11) DEFAULT NULL,
  `BUYOTHER` int(11) DEFAULT NULL,
  `INCOME8` int(11) DEFAULT NULL,
  PRIMARY KEY (`row`),
  KEY `FS_ID_index` (`FS_ID`),
  KEY `MEM_ID_index` (`MEM_ID`),
  KEY `FM_MM_index` (`FM_MM`)
) ENGINE=InnoDB AUTO_INCREMENT=21694 DEFAULT CHARSET=utf8;


*/}

@F public Integer row
,FS_ID
,RECORD_ID
,TABLE_ID
,FSCYCLE
,MEM_ID
,FM_MM//` varchar(1) DEFAULT NULL,
,SALRY_1
,SALRY_2
,BONCE_1
,BONCE_2
,ALLOW_1
,ALLOW_2
,INCOME1
,INDUST
,COMMERCE
,TRANS
,CONSTRANT
,FAINANCE
,OWNWRK
,OTHERS
,INCOME2
,DIVIDENDS
,BONDS
,SAVINGAC
,INVESTMENT
,INCOME3
,LANDRENT
,PROJCTRENT
,MACHNRENT
,CPYRIGHT
,INCOME4
,MARIGGIFT
,RETIREDSAL
,TRETGRANT
,SOCILASST
,UNEMPALOW
,RENTALLOW
,OTHRGRANT
,INCOME5
,ACC_COMP
,LIFEINSUR
,REMTABROD
,REMTINSDE
,LEGITEXP
,CASHGIFT
,KINDGIFT
,INCOME6
,CSHINHERIT
,DOWRY
,SATELDLOAN
,SELGOODS
,LIFEINSRNC
,WITHDRAWS
,OTHERPROC
,INCOME7
,DEPOSIT
,WITHDRAW
,LENDING
,BORRWING
,PROCEEDS
,PAYMENTS
,SELSCRTIS
,BUYSCRTIS
,SELLAND
,BUYLAND
,SELBUILD
,BUYBUILD
,SELOTHER
,BUYOTHER
,INCOME8;
@Override public String getName() {return dbtName;}


public enum C implements CI{
	row
	,FS_ID
	,RECORD_ID
	,TABLE_ID
	,FSCYCLE
	,MEM_ID
	,FM_MM
	,SALRY_1
	,SALRY_2
	,BONCE_1
	,BONCE_2
	,ALLOW_1
	,ALLOW_2
	,INCOME1
	,INDUST
	,COMMERCE
	,TRANS
	,CONSTRANT
	,FAINANCE
	,OWNWRK
	,OTHERS
	,INCOME2
	,DIVIDENDS
	,BONDS
	,SAVINGAC
	,INVESTMENT
	,INCOME3
	,LANDRENT
	,PROJCTRENT
	,MACHNRENT
	,CPYRIGHT
	,INCOME4
	,MARIGGIFT
	,RETIREDSAL
	,TRETGRANT
	,SOCILASST
	,UNEMPALOW
	,RENTALLOW
	,OTHRGRANT
	,INCOME5
	,ACC_COMP
	,LIFEINSUR
	,REMTABROD
	,REMTINSDE
	,LEGITEXP
	,CASHGIFT
	,KINDGIFT
	,INCOME6
	,CSHINHERIT
	,DOWRY
	,SATELDLOAN
	,SELGOODS
	,LIFEINSRNC
	,WITHDRAWS
	,OTHERPROC
	,INCOME7
	,DEPOSIT
	,WITHDRAW
	,LENDING
	,BORRWING
	,PROCEEDS
	,PAYMENTS
	,SELSCRTIS
	,BUYSCRTIS
	,SELLAND
	,BUYLAND
	,SELBUILD
	,BUYBUILD
	,SELOTHER
	,BUYOTHER
	,INCOME8
	;
	@Override public Class<? extends Tbl>cls(){return Income.class;}
	@Override public Class<? extends Form>clss(){return cls();}
	@Override public String text(){return name();}
	@Override public Field f(){return Cols.f(name(), cls());}
	@Override public Tbl tbl(){return Tbl.tbl(cls());}
	@Override public void save(){tbl().save(this);}
	@Override public Object load(){return tbl().load(this);}
	@Override public Object value(){return val(tbl());}
	@Override public Object value(Object v){return val(tbl(),v);}
	@Override public Object val(Form f){return f.v(this);}
	@Override public Object val(Form f,Object v){return f.v(this,v);}
}//C

@Override public CI pkc(){return C.row;}
@Override public Object pkv(){return row;}
@Override public CI[]columns(){return C.values();}
public static final String dbtName="Income";

}//class Income Tbl
